name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies and activate envinronment
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m poetry install
          source .venv/bin/activate
          python -m poetry build
