name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Cache poetry virtualvenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock')}}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock')}}
      - name: Set poetry config
        run: |
          poetry config virtualenvs.path ~/.virtualenvs
      - name: Install deps
        run: poetry install
        if: steps.cache.output.cache-hit != 'true'
      - name: Linting
        run: poetry run pylint **/*.py
      - name: Testing
        run: poetry run pytest --cov=nmh tests/
